#!/usr/bin/env bash
# Configure HAProxy to balance traffic between web-01 and web-02 using a roundrobin algorithm.

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    timeout client 30s

backend webservers
    mode http
    balance roundrobin
    server 530884-web-01 107.23.101.78:80 check
    server 530884-web-02 18.206.233.53:80 check
    timeout connect 10s
    timeout server 30s
"

# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Backup original HAProxy configuration file
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Update HAProxy configuration
echo "$balancer" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAProxy to start on boot
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Testing the HAProxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart

# Ensure the HAProxy service starts on boot
sudo systemctl enable haproxy
