#!/usr/bin/env bash
# This script installs and configures HAProxy on lb-01 server to send traffic to web-01 and web-02 servers using roundrobin algorithm.

# Update and install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Edit config file
server_config=$(cat <<EOF
frontend besthor_frontend
    bind *:80
    mode http
    default_backend besthor_backend

backend besthor_backend
    balance roundrobin
    server 530884-web-01 107.23.101.78:80 check
    server 530884-web-02 18.206.233.53:80 check
EOF
)

echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo systemctl restart haproxy

# Ensure the HAProxy service starts on boot
sudo systemctl enable haproxy
